openapi: 3.0.0
x-stoplight:
  id: gr0crptnshajn
info:
  title: AzureIsland--teacher-api
  version: '1.0'
servers:
  - url: 'http://localhost:9000'
paths:
  /school-admin/teachers:
    get:
      summary: get-teachers
      tags: []
      responses: {}
      operationId: get-school-admin-teachers
  '/school-admin/teacher/{teacherId}':
    parameters:
      - schema:
          type: string
        name: teacherId
        in: path
        required: true
      - schema:
          type: string
        name: teacherId
        in: path
        required: true
    get:
      summary: get-teacher
      tags: []
      responses: {}
      operationId: get-school-admin-teacher-teacherId
    put:
      summary: put-teacher
      tags: []
      responses: {}
      operationId: put-school-admin-teacher-teacherId
    delete:
      summary: delete-teacher
      tags: []
      responses: {}
      operationId: delete-school-admin-teacher-teacherId
  /school-admin/teacher:
    post:
      summary: post-teacher
      tags: []
      responses: {}
      operationId: post-school-admin-teacher
  /school-admin/student:
    post:
      summary: post-student
      tags: []
      responses: {}
      operationId: post-school-admin-student
  /school-admin/students:
    get:
      summary: get-students
      tags: []
      responses: {}
      operationId: get-school-admin-students
  '/school-admin/student/{studentId}':
    parameters:
      - schema:
          type: string
        name: studentId
        in: path
        required: true
    get:
      summary: get-student
      tags: []
      responses: {}
      operationId: get-school-admin-student-studentId
    put:
      summary: put-student
      tags: []
      responses: {}
      operationId: put-school-admin-student-studentId
    delete:
      summary: delete-student
      tags: []
      responses: {}
      operationId: delete-school-admin-student-studentId
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
